### ISSUE TITLE
WMIWifi_Info

### ISSUE THREAD

**Issue by limelect** [RRUZ/blog#1]
GetWiFi_NetworkAdapterInfo    FWbemObjectSet:= FWMIService.ExecQuery('SELECT \* FROM WiFi_NetworkAdapter','WQL',wbemFlagForwardOnly);

Delphi  7   window 7  error invalid class

**Comment by RRUZ** [comment]
Assuming which you are using the code listed here  https://theroadtodelphi.wordpress.com/2011/10/15/all-about-wifi-networks-and-wifi-adapters-using-the-wmi-and-delphi/

This is the answer : In order to work with these _WMI_ classes your Wifi Network adapter must install a _CIMWiFiProvider_ which implement these classes. The _CIMWiFiProvider_ is installed when you install the driver of your Wifi network adapter. Try checking the site of the manufacter of your network card.
